### ISSUE TITLE
Update to Laravel 8

### ISSUE THREAD

**Issue by supertassu** [UTRS2/utrs#103]
Currently we are using Laravel 6.18.35 (as of 2020-09-08) even thru 8 is the newest version. I'll do the upgrade when I have time.

**Comment by dqwiki** [comment]
No support for it in our version of tinker, waiting on #195

**Comment by supertassu** [comment]
[Laravel 8](https://laravel.com/docs/8.x/releases) was released today. By a pure coincidence the version we are using (6) is an LTS version so we aren't in a hurry to upgrade but it would be quite useful to be able to use new features.

**Comment by supertassu** [comment]
Update plan:

First, bump dependencies, apply most changes in the application boilerplate and fix immediate breakage (#285)

After that handle other post-update steps:
* Move models into `app/Models` and also handle #139 (#291)
* Handle tickets that would need significant changes due to the update, such as 288
* Make changes that make use of new features, such as job chains, specific route parameters...
