### ISSUE TITLE
Differentiate between appeals who have been sent a verification email and those who dont

### ISSUE THREAD

**Issue by supertassu** [UTRS2/utrs#116]
The appeal view should display a different message for users who have been sent a verification email (`verify_token` is not null) and users who can't be emailed for some reason or haven't been emailed yet.

**Comment by SidChat93** [comment]
Appeals for which the blocked user have been sent an email to will have the comment '_Action: account verifed_' from '_System_'

**Comment by dqwiki** [comment]
Handled this this past week.
