### ISSUE TITLE
Autoblock IDs taken as accounts

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#123]
In the verify block script, autoblocks, or the block number is taken as an account name and doesn't get verified. They all start with "#" so that is the identifier.

**Comment by supertassu** [comment]
I believe the only problem is that the script doesn't remove '#' from the beginning:

https://github.com/UTRS2/utrs/blob/775e62c65451d6b439ca5d2412d102fcd8af6548/app/Jobs/GetBlockDetailsJob.php#L70

**Comment by dqwiki** [comment]
@supertassu 
Mediawiki/Api/UsageException with message 'Code: baduser
Message: Invalid value "#{redacted}" for user parameter "bkusers".
Result: {"error":{"code":"baduser","info":"Invalid value /"#{redacted}/" for user parameter /"bkusers/".","*":"See https:////en.wikipedia.org//w//api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https:////lists.wikimedia.org//mailman//listinfo//mediawiki-api-announce&gt; for notice of API deprecations and breaking changes."},"servedby":"mw1343"}'

**Comment by dqwiki** [comment]
The # is required to validate the block, but not under bkusers, but bkids

**Comment by supertassu** [comment]
@dqwiki See my PR above, actually in addition to that there was another bug that somehow hid the first bug.
