### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by vanjagenije** [UTRS2/utrs#142]
I am an admin. I received an e-mail for account confirmation. When I follow the link, I get a message "Uh-oh. UTRS has suffered an internal exception and can't continue to serve your request."

**Comment by dqwiki** [comment]
We had a lapse in the database today, so I can't investigate it until I have you try again. If you do have issues, can you upload a screenshot without the end of the URL showing your confirmation code?

**Comment by vanjagenije** [comment]
It's still reporting the same problem.
    On Sunday, May 24, 2020, 04:17:43 AM GMT+2, dqwiki <notifications@github.com> wrote:  
 
 


We had a lapse in the database today, so I can't investigate it until I have you try again. If you do have issues, can you upload a screenshot without the end of the URL showing your confirmation code?

**Comment by dqwiki** [comment]
Sorry I forgot to say that you would have to reregister, the database doesn't have your account right now.

**Comment by dqwiki** [comment]
According to the database, you have a verified account now.

**Comment by vanjagenije** [comment]
Yes, I can log in now, but I still can't see any request.
When I click on any request, I receive this message "The appeal you are trying to access is currently being reviewed by the privacy team. You do not have sufficient permissions to view it."

**Comment by supertassu** [comment]
@vanjagenije This should now be fixed, can you try again?

**Comment by vanjagenije** [comment]
It's not working. I can't access the service at all. I'm receiving this message: 503
OAuth Upgrade

**Comment by dqwiki** [comment]
@vanjagenije Yes, we are in the middle of an OAuth upgrade, that is a maintenance message, not an error. We'll be done soon.
