### ISSUE TITLE
OAuth is broken on live server

### ISSUE THREAD

**Issue by supertassu** [UTRS2/utrs#175]
OAuth login has broken on the live site (utrs-beta.wmflabs.org) after merging #173. My suspicion is that the added dependency is missing due to a broken `composer.lock` file on the server. @dqwiki please remove that file and install dependencies again.

**Comment by dqwiki** [comment]
To have a log of this:

> Package operations: 1 install, 8 updates, 0 removals
>  - Updating doctrine/cache (1.10.0 => 1.10.1): Downloading (100%)
>  - Updating doctrine/inflector (2.0.2 => 2.0.3): Downloading (100%)
>  - Updating symfony/service-contracts (v2.0.1 => v2.1.2): Downloading (100%)     
>  - Updating symfony/translation-contracts (v2.0.1 => v2.1.2): Downloading (100%)
>  - Updating nesbot/carbon (2.34.2 => 2.35.0): Downloading (100%)
>  - Updating laravel/framework (v6.18.15 => v6.18.16): Downloading (100%)         
>  - Updating laravel/dusk (v6.1.0 => v6.2.0): Downloading (100%)
>  - Updating justinrainbow/json-schema (5.2.9 => 5.2.10): Downloading (100%)      
>  - Installing taavi/laravel-socialite-mediawiki (1.0.0): Downloading (100%)

**Comment by dqwiki** [comment]
OAuth login is working.
