### ISSUE TITLE
I can't appeal a Wikipedia block

### ISSUE THREAD

**Issue by RejsHajredini95** [UTRS2/utrs#189]
Hi dear users!

My Wikipedia account was blocked and I submitted an unblock request at https://utrs-beta.wmflabs.org/ but when I enter my key it appears an error:

Oops. This page was not found.
If an internal link lead you here, please report this at https://github.com/utrs2/utrs/issues.

Please let me know what's the issue and if can be fixed.

Thank you

**Comment by supertassu** [comment]
Hi @RejsHajredini95. Have you verified that you haven't accidentally included spaces at the beginning or end of the appeal key?

**Comment by RejsHajredini95** [comment]
> Hi @RejsHajredini95. Have you verified that you haven't accidentally included spaces at the beginning or end of the appeal key?

Yes

**Comment by dqwiki** [comment]
It is difficult for us to look into this without knowing what user or IP you appealed for. Could you please let us know?

**Comment by RejsHajredini95** [comment]
> It is difficult for us to look into this without knowing what user or IP you appealed for. Could you please let us know?

https://en.wikipedia.org/wiki/User:RejsHajredini95

**Comment by dqwiki** [comment]
There is no appeal by that name in our database, and they are not deleted at all. If you want to try emailing the developers email with the secret key you got, I can see if your key is in the database.

**Comment by RejsHajredini95** [comment]
> There is no appeal by that name in our database, and they are not deleted at all. If you want to try emailing the developers email with the secret key you got, I can see if your key is in the database.

My appeal key is: ~~please do not post this publicly, thanks!~~

**Comment by dqwiki** [comment]
We have looked every where for your appeal and could not find anything at all. You will need to refile at this point. There is no appeal key or appeal name for either of what you provided.

Please note: Due to database issues all data from April 29 to May 23 has been lost. If you are trying to access an appeal and get an error, you will need to file your appeal again.

**Comment by GrooveyDude** [comment]
I was banned from UTRS... I think my number is #138
