### ISSUE TITLE
Viewing closed appeals

### ISSUE THREAD

**Issue by Callanecc** [UTRS2/utrs#19]
Currently I can't see closed appeals - I get an error message about not having the right permissions. Admins at least should be able to see closed appeals for background on an editor and the context of their appeal.

**Comment by dqwiki** [comment]
@Callanecc this is supposed to be working. I tried to reproduce it by using the same permissions you have and don't seem to have the error. Can you give me an example appeal number your having the issue with?

**Comment by Callanecc** [comment]
@dqwiki Hmm, looks like it's working now. :)
