### ISSUE TITLE
Add a way to bypass the appeal-per-ip limit on test instances

### ISSUE THREAD

**Issue by examknow** [UTRS2/utrs#209]
There is currently a limit of one appeal per IP on the UTRS system. While this is a good thing to prevent abuse in production, it is a giant pain to have to change the IP in the database when testing. I am recommending that there is a config flag that can be set to disable this limit on testing instances.

**Comment by supertassu** [comment]
Blocked on #158.

> I am recommending that there is a config flag that can be set to disable this limit on testing instances.

Probably just easier to check if `APP_ENV` is set to `local`.

**Comment by examknow** [comment]
> Blocked on #158.
> 
> > I am recommending that there is a config flag that can be set to disable this limit on testing instances.
> 
> Probably just easier to check if `APP_ENV` is set to `local`.

Works for me

**Comment by ST15392** [comment]
```php
$wgappealratelimit = 8; // x per ip per minute'
```
