### ISSUE TITLE
Stewards are no longer able to view appeals

### ISSUE THREAD

**Issue by Tks4Fish** [UTRS2/utrs#230]
Stewards are no longer able to view appeals on the list, or by accessing them directly. That was possible before the move to OAuth.

**Comment by supertassu** [comment]
This bug was probably introduced as a side effect of #106. Technically this can just be fixed by adding stewards (and staff, probably) to AppealPolicy but I wonder if it would be better to just modify `Permission::hasAnySpecifiedPerms()` to count steward/staff rights as sysop rights.
