### ISSUE TITLE
UTRS 1 appeals search returning page not found.

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#236]
Oldappeal::findOrFail() works fine...it's something else.

**Comment by supertassu** [comment]
In case you're referring to https://en.wikipedia.org/w/index.php?title=Template:UTRS&diff=prev&oldid=965788999&diffmode=source you also have to change the rest of the URL

**Comment by dqwiki** [comment]
No it doesn't work in tool either by entering the appeal number

**Comment by dqwiki** [comment]
So it is just the search function on the main page, now that the appeals have the right URL.

**Comment by supertassu** [comment]
... just realized what caused this. fix incoming

**Comment by dqwiki** [comment]
Saves me dumpster diving :D

**Comment by supertassu** [comment]
In case you're curious, this was caused by

https://github.com/UTRS2/utrs/blob/dd19a24ea2d20daa3295659fd7889a393fc03587/app/Http/Controllers/AppealController.php#L202

that wasn't changed when implementing old appeals to search.
