### ISSUE TITLE
Assess alternatives for mysql service in PRs

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#252]
MySQL takes over a minute to start up in pull request times, making reviews extremely long. Would SQLLite provide faster implementation since that is already covered by Laravel?

**Comment by supertassu** [comment]
#254 changes MySQL to MariaDB. I have no idea why but it seems to be faster (~40s vs ~1m).

**Comment by dqwiki** [comment]
254 merged MariaDB as best option.
