### ISSUE TITLE
Duplicate appeal block failing

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#255]
Users are able to file multiple appeals, in this case, 4 appeals in 4 seconds. There used to be a mechanism preventing duplicate appeals for 48 hours.

**Comment by supertassu** [comment]
https://github.com/UTRS2/utrs/blob/8d1bde2a9bc31a768f30051b397ee5a9a9e882b0/app/Http/Controllers/Appeal/PublicAppealController.php#L40-L51

that SHOULD present doing this. @dqwiki  were the separate appeals for the same or different target (appealfor)?

**Comment by dqwiki** [comment]
Same appealfor as far as I can tell. There was no appeal modification for the block target either.

**Comment by dqwiki** [comment]
We've made a lot of changes with this area, and as far as I am aware, I haven't seen any issue since. I'll close this for now.
