### ISSUE TITLE
A Little Request

### ISSUE THREAD

**Issue by Iyarita** [UTRS2/utrs#275]
This is Skiyomi from the English Wikipedia. I would really like to ask to have my block lifted there through the UTRS system (since the stewards have told me that I have to get unblocked on Wikipedia before they'll unlock my global account), but right now I am banned from UTRS until January 1. I was wondering if my UTRS ban (ID: 13) could please be lifted so I can appeal my block? I will address the reasons I was blocked and any other concerns the admins might have. And I won't use any bad language there. Thank you.

-Skiyomi

**Comment by supertassu** [comment]
You can't appeal UTRS bans here, GitHub is only used for reporting software bugs and requesting for features.
