### ISSUE TITLE
Appeal list not generating

### ISSUE THREAD

**Issue by GeneralNotability** [UTRS2/utrs#320]
Discussed with @dqwiki on IRC - no appeals are showing up for me, but if given a link to a specific appeal I can view it. I've logged out and logged back in, cleared browser cache, and forced a permissions update (my permissions correctly show enwiki user + sysop), no dice for any of them.

**Comment by dqwiki** [comment]
This shows the users current permission table. There are no duplicate entries in the database.

![screenshot 198](https://user-images.githubusercontent.com/676350/97495296-d5775880-193d-11eb-9f5e-5af7da6ceca2.jpg)

**Comment by dqwiki** [comment]
Attempted testing so far:

- Duplication of user permissions
- Minimal user permissions
- App Cache clearing
- Brief revert to 44664cf

Facts: 
- User has no wikis listed on user table (expected); testing revealed this shouldn't matter
- Unable to replicate live or in local environments
- Wikis are still listed appropriately on Appeals table
- Status and block type vary for open appeals that should show
- No errors showing in the error logs

**Comment by supertassu** [comment]
> User has no wikis listed on user table (expected); testing revealed this shouldn't matter

@dqwiki You sure?
https://github.com/UTRS2/utrs/blob/e541641e06118864af8404165597ee4467e10fec/app/Http/Controllers/AppealController.php#L122

**Comment by dqwiki** [comment]
Not 100% sure on my comment, but I seemingly removed them from my user the other day and only had admin flags and I still saw things.
