### ISSUE TITLE
Can't appeal an IP block: "The POST method is not supported for this route. Supported methods: GET, HEAD. "

### ISSUE THREAD

**Issue by supertassu** [UTRS2/utrs#34]
**Steps to reproduce**:
* Be logged out
* On the front page, click "Appeal IP block"
* Fill in some IP address and some reason and submit

**Expected result**:
* appeal is created

**Actual result**:
* an error appears, saying "The POST method is not supported for this route. Supported methods: GET, HEAD."

**Comment by dqwiki** [comment]
Well this explains why there has been no IP appeals...apparently I never coded it

**Comment by dqwiki** [comment]
I'm going to do a hacky copy paste to get it running, but it really should be cleaned up. @supertassu can I get you to create a new issue to clean it up?

**Comment by dqwiki** [comment]
Actually, I found a way around this. It's only a couple line modification, closing #35
