### ISSUE TITLE
Periodically automatically refresh user permissions

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#361]
WMF Staff (who aren't sysops on enwiki) are not able to get into the system. Permission refresh does nothing and they don't get flagged.

**Comment by supertassu** [comment]
Oh, this is a really stupid issue... the `steward` group is also a local group on meta, but the `staff` group isn't...

**Comment by dqwiki** [comment]
> Notice: You do not have the necessary permissions to view appeals on any queues.

This was reported by a staff member.

**Comment by supertassu** [comment]
Can't reproduce:
![image](https://user-images.githubusercontent.com/9721638/100709064-1a1b6700-33b6-11eb-8cca-ee9293e687c9.png)


![image](https://user-images.githubusercontent.com/9721638/100709102-2dc6cd80-33b6-11eb-8e7b-5b86824773a6.png)


Please ask them to refresh their permissions. (should we do that automatically?)

**Comment by dqwiki** [comment]
Permission refresh resolved, it might be a good thing to do on a regular basis to make sure on-wiki matches on the tool.

**Comment by Endymiona** [comment]
Hcchhcvjjvjvih

**Comment by Endymiona** [comment]
Fghjnkihvgf
