### ISSUE TITLE
Fail login due to mediawiki API code

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#365]
OAuth failed: MediaWiki api returned an invalid user object {"token":null,"tokenSecret":null,"id":null,"nickname":null,"name":"AmandaNP","email":null,"avatar":null,"user":{"name":"AmandaNP","groups":["patroller","translationadmin","","user","autoconfirmed"]},"groups":["patroller","translationadmin","","user","autoconfirmed"]}
Level
ERROR

**Comment by dqwiki** [comment]
> HEAD is now at 03935b6 Fix retrieving global rights (#363)

For the time being

**Comment by supertassu** [comment]
Did you update composer dependencies after merging #356? That updated taavi/laravel-socialite-mediawiki to 1.3 which is required for storimg user ids
