### ISSUE TITLE
Show previous appeals in a table

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#37]
Previous appeals by user and by ip should be listed on the appeal directly, not including itself.

Searching for account appeals only has to worry about appealfor in appeals table.
Searching for other IP appeals has to worry about both appealfor and hiddenip in the appeals table. It would also be prudent to search in the logs table under:
`{ user = 0, objecttype = appeal, action = create, ip = {ip} }`

Can I have you do this @supertassu ? I'm also going to add you to the project so we can add you to assign.

**Comment by supertassu** [comment]
Sure, I'll do this sometime this week!
