### ISSUE TITLE
I can't appeal unblock my account on Wikipedia

### ISSUE THREAD

**Issue by Jasimrizvi** [UTRS2/utrs#448]
Please help me. I can't appeal to unblock my account to Wikipedia. when I'm going to send a request to unblock my account this message/error has been accrued. 

**"It has been detected that you or someone else is trying to spam our system with appeals. Please wait until your previous appeal is closed, or if it's already closed, please try again later.

If you are applying for an unblock of an IP address, this could mean that an appeal has already been submitted for your IP. In this case, please try again later or contact us to help clarify the issue."**

Please tell me someone what can I do?

Thankyou!

**Comment by supertassu** [comment]
The system intentionally requires you to wait a few days between appeals to prevent flooding the system. Please wait a few days, check that the appeal is something that you still want to submit, and re-submit your appeal. This is a feature, not a bug.
