### ISSUE TITLE
Releasing an appeal removes it from the CU queue

### ISSUE THREAD

**Issue by SQL-enwiki** [UTRS2/utrs#455]
If one reserves a checkuser appeal in order to ask the user a question, then releases it - it is removed from the CU queue, and has to be re-added.

**Comment by supertassu** [comment]
Could you please make sure at which point does the appeal status change? Appeal release doesn't change appeal status at all, so I'm thinking that the appeal might have moved to the `OPEN` (practically meaning removed from the CU queue) if the CU added a response which included a status change.

**Comment by SQL-enwiki** [comment]
Example of when this happened: https://utrs-beta.wmflabs.org/appeal/41830

**Comment by supertassu** [comment]
I don't have access to the production system to see what's happening on that appeal, but I think I have an idea and #459 should fix it.
