### ISSUE TITLE
Need to submit new appeal

### ISSUE THREAD

**Issue by WndrLck44** [UTRS2/utrs#457]
I am in need of submitting a new appeal for Wiki and am unable to. How can this be resolved?

**Comment by Endymiona** [comment]
What message do you get? I know that after an appeal is closed, there is around a 48-hour "cooldown" before you can open another one.

**Comment by supertassu** [comment]
Please include the full error message (and follow the instructions on the error message!) and any necessary steps to reproduce when reporting bugs. Closing this report as those are missing.
