### ISSUE TITLE
Trying to create Wikipedia Account - Got Exception error

### ISSUE THREAD

**Issue by windypoint** [UTRS2/utrs#463]
I am trying to create a Wikipedia account but got blocked. The IP being blocked is not mine unless it from HostGator, who is my ISP. I can't create a Wikipedia-en account, which I wish to do, to update a section of a page. I do use a VPN, but I turned it off after I got the blocked message. Still, I can't create an account. I could provide my VPN IP address or my actual IP address if you need it. Any help or guidance you could provide would be greatly appreciated.
Thank you...

Steve Blackson
steve@windypoint.com

**Comment by dqwiki** [comment]
We don't deal with any appeals here, we just deal with the technical issues with the UTRS software.
