### ISSUE TITLE
try to send an appeal but error happened

### ISSUE THREAD

**Issue by hrafiee** [UTRS2/utrs#466]
after I tried to send a new appeal, I was told that I am unable to send any appeal because I already have an open appeal. although there is no open appeal available

**Comment by hrafiee** [comment]
This is the content of error message

It has been detected that you or someone else is trying to spam our system with appeals. Please wait until your previous appeal is closed, or if it's already closed, please try again later.

If you are applying for an unblock of an IP address, this could mean that an appeal has already been submitted for your IP. In this case, please try again later or contact us to help clarify the issue.

**Comment by dqwiki** [comment]
This is not a bug, but a feature meant to prevent appeals from being redone within a certain timeframe.
