### ISSUE TITLE
Appeal closed, but error

### ISSUE THREAD

**Issue by Brothernotuser1** [UTRS2/utrs#467]
It says to wait until the apeal is closed but it is already closed.

**Comment by SidChat93** [comment]
I have also faced it. When I made my first appeal I forgot my appeal key. So, it told me that I cannot file another appeal. I saw that my appeal is still open on https://en.wikipedia.org/wiki/Category:Requests_for_unblock#UTRS_appeals. I waited, then I got a message on my talk page at https://en.wikipedia.org/wiki/User_talk:SidChat2048#UTRS_48613 that it was closed. It told me to wait for six months.

**Comment by Brothernotuser1** [comment]
> I have also faced it. When I made my first appeal I forgot my appeal key. So, it told me that I cannot file another appeal. I saw that my appeal is still open on https://en.wikipedia.org/wiki/Category:Requests_for_unblock#UTRS_appeals. I waited, then I got a message on my talk page at https://en.wikipedia.org/wiki/User_talk:SidChat2048#UTRS_48613 that it was closed. It told me to wait for 6 months.
Thanks.

**Comment by SidChat93** [comment]
Here is my appeal:

https://utrs-beta.wmflabs.org/public/appeal/view?hash=17173f12efa345dcb4d93479f2225c14

**Comment by SidChat93** [comment]
> I have also faced it. When I made my first appeal I forgot my appeal key. So, it told me that I cannot file another appeal. I saw that my appeal is still open on https://en.wikipedia.org/wiki/Category:Requests_for_unblock#UTRS_appeals. I waited, then I got a message on my talk page at https://en.wikipedia.org/wiki/User_talk:SidChat2048#UTRS_48613 that it was closed. It told me to wait for 6 months.

When the appeal closed, I tried to file another appeal, but I got the same message as yours.

**Comment by SidChat93** [comment]
I deleted the comment you edited since the link was made useless.

**Comment by Endymionaaa** [comment]
for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas

**Comment by TheBestUser01234567890** [comment]
Hello, my old account.
