### ISSUE TITLE
Fix viewing of old appeals

### ISSUE THREAD

**Issue by supertassu** [UTRS2/utrs#47]
Currently viewing old appeals results in a 500. I have a strong feeling it is caused by this as e-mail might be null:

https://github.com/UTRS2/utrs/blob/b2bf722ceb9057f305f3d8faa64e60b6680ec9a9/resources/views/appeals/oldappeal.blade.php#L22

**Comment by dqwiki** [comment]
This is considered privatedata in the old system and really shouldn't have been ported over.
