### ISSUE TITLE
Update live systems to Debian Bullseye

### ISSUE THREAD

**Issue by supertassu** [UTRS2/utrs#475]
Debian 11 (bullseye) is now out and available in Cloud VPS, it's time to update [our instances](https://openstack-browser.toolforge.org/project/utrs) running anchient Debian 9 (stretch). While stretch [still has some lifetime remaining in WMCS](https://lists.wikimedia.org/hyperkitty/list/cloud-announce@lists.wikimedia.org/thread/2PG3OFP4VU3UEQ237QVQO3K4XR6GQ7OD/), we should update at least the application servers sooner than later since we'll need to update to bullseye anyways (since Debian 12 is years away at this point) and it gives us a newer PHP version that most dependencies are starting to require.

**Comment by Endymiona** [comment]
Xfhjgfghii

**Comment by dqwiki** [comment]
Debian 11 is fighting with me as mysql-server is not supported for it, and even manually trying to install it, I get:
> E: The repository 'http://repo.mysql.com/apt/debian buster InRelease' is not signed.

The other option is to go with MariaDB, the default for debian 11. Thoughts?

**Comment by supertassu** [comment]
MariaDB is what I prefer, let's go with that :-)

**Comment by dqwiki** [comment]
All done :)
