### ISSUE TITLE
Issue with block appeal

### ISSUE THREAD

**Issue by ZaphodScotsman** [UTRS2/utrs#486]
I tried to make a Wikipedia block appeal but I keep getting this message:

It has been detected that you or someone else is trying to spam our system with appeals. Please wait until your previous appeal is closed, or if it's already closed, please try again later.

If you are applying for an unblock of an IP address, this could mean that an appeal has already been submitted for your IP. In this case, please try again later or contact us to help clarify the issue.

this simply isn’t true: nobody is spamming the system. Waiting a day didn’t help, does anybody know how to fix this glitch?

**Comment by Endymiona** [comment]
I think you have to wait 48 hours, at least from my experience.

**Comment by Endymiona** [comment]
> 

Please stop impersonating me AMD saying bad things about the Wikipedia admins. They do not deserve that and I don't appreciate you using my name to say that.

**Comment by Endymionaaaa** [comment]
for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas for yamlafuck pooyo and deepfuckfuck to jump off a bridge and die as soon as possible and to free skiyomi and other ltas

**Comment by ZaphodScotsman** [comment]
He said stop for crying out loud!

**Comment by Endymiona** [comment]
I reported them to Github for impersonating me (using a name almost identical to mine) so I think that's all I can do. I can't report this to the Wikipedia admins as my account is blocked and globally locked.
