### ISSUE TITLE
Fix appeal commenting from blocked user

### ISSUE THREAD

**Issue by supertassu** [UTRS2/utrs#52]
Currently, if you are the blocked user and add a comment to your appeal, you will be redirected to logged in user's view of appeal giving you a 403. This a) is a bad user experience and b) can cause confusion about if your comment was submitted or not.

The problem here will be redirecting back to POST endpoint, more specifically the same problem as at https://github.com/UTRS2/utrs/pull/33#discussion_r423638208. I'm not sure what `redirect()->back()` does with that (not an option at that other case linked below), I'll take a look at that when I have time.

**Comment by dqwiki** [comment]
This is tricky because it has to be post from the initial view, but we still need to identify based on the appeal key.

Is there some way to force the post from the main page into a get on a URL w/ the appeal key? I think i'm dreaming.

**Comment by dqwiki** [comment]
Maybe a short term cookie?

**Comment by supertassu** [comment]
> Is there some way to force the post from the main page into a get on a URL w/ the appeal key?

HTTP GET will produce something like `/publicappeal?hash=123456789012345678901234567890`
