### ISSUE TITLE
Página da Wikipedia bloqueada e pedido de recurso sendo negado

### ISSUE THREAD

**Issue by athossalome** [UTRS2/utrs#531]
Bom dia! Solicito gentilmente que minha página seja desbloqueada. Inúmeras vezes descrevi que infelizmente não sei usar a plataforma da Wikipedia e uma pessoa criou a minha página, alegando que sabia trabalhar e construir algo significativo.
Tenho as provas de conversas, mas não vejo o campo aqui para anexar e provar que estou sendo injustiçado.
Apenas estou recorrendo ao meu direito, sou uma pessoa pública e quero fazer as devidas correções com um bom profissional.
Meu nome é a única coisa que tem valor e que prezo.
A mais de um mês estou bloqueado. Preciso que confiem em mim para que um bom profissional, editor fazer as devidas correções.
Se digitarem no google, vai encontrar inúmeros artigos orgânicos sobre mim, nada promocional.
Não preciso de aparecer, apenas quero registrar e afirmar que sou único.

Muito obrigado e estou a disposição para esclarecimentos.

**Comment by Endymiona** [comment]
Ufigogogog
