### ISSUE TITLE
Incorrect transcribed key. Please help 

### ISSUE THREAD

**Issue by Yeahthatsright1** [UTRS2/utrs#539]
Doing an appeal need correct appeal key. Transcribed incorrectly. The submission won't let me do another to obtain a different key. Need to recover mine.

**Comment by Salvidrim** [comment]
Copying comment from same user from duplicate issue #540 


> [Yeahthatsright1](https://github.com/Yeahthatsright1) commented [on Jan 30](https://github.com/UTRS2/utrs/issues/540#issue-1118741519)
> Doing an appeal need correct appeal key. Transcribed incorrectly. The submission won't let me do another to obtain a different key. Need to recover mine.
