### ISSUE TITLE
typo in notice about UTRS 1.8

### ISSUE THREAD

**Issue by Grahamwp** [UTRS2/utrs#547]
"Backwards compatability is available for viewing only" should be "Backwards compatibility is available for viewing only". I found this in the old appeal #22835, which is linked from a block log.

**Comment by Salvidrim** [comment]
The typo is in [utrs/resources/views/appeals/oldappeal.blade.php](https://github.com/UTRS2/utrs/blob/c5e6eab5c4e6fe0c67c762629c9c3d40e22e03fa/resources/views/appeals/oldappeal.blade.php)

I tried filing a pull request myself to fix it but I think I don't have access to create branches on this repo and creating a whole fork to pull just for a typofix seems heavy-handed. (Or maybe I'm misunderstanding GitHub proper practices :p)

**Comment by dqwiki** [comment]
Fixed in [bbba47c](https://github.com/UTRS2/utrs/commit/bbba47cbfd364c7750130ce804059f78db5e8521)
