### ISSUE TITLE
typo in account verification message

### ISSUE THREAD

**Issue by Grahamwp** [UTRS2/utrs#548]
I've found another typo: "account verifed" should be "account verified" in, say, this block appeal:
https://utrs-beta.wmflabs.org/appeal/56475

**Comment by Salvidrim** [comment]
The typo is in [app/Http/Controllers/Appeal/PublicAppealController.php](https://github.com/UTRS2/utrs/blob/d89ef133ece33747fbfb8195b4d79b1dc95418c9/app/Http/Controllers/Appeal/PublicAppealController.php) on line 182

**Comment by dqwiki** [comment]
Since it's a DB function, I've fixed it for the future, but I haven't gone through the database to fix it.
