### ISSUE TITLE
Appeals stuck in verify not expiring

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#549]
Appeals that are stuck in VERIFY status, because something is not working with the verification are not expiring. Most of the time, it's invalid IP addresses and extraneous text.

**Comment by supertassu** [comment]
Appeals should not be stuck in VERIFY at all, the verification logic should move those to OPEN or NOTFOUND as soon as they are checked. The code for expiring appeals is only closing NOTFOUND ones without any activity.

**Comment by dqwiki** [comment]
We have appeals from 2021-06-25 00:07:55 to 2022-02-12 17:04:27 that are all stuck in verify. It's only 10 appeals, but none should be getting stuck. I'll try and reverify tomorrow and see if any errors pop up.

**Comment by dqwiki** [comment]
So the issue is with the format of the bkusers being put into the API, and that API is throwing the error. I tried catching it, but that doesn't seem to work.

**Comment by dqwiki** [comment]
Looks like this could be handled by instead getting the mediawiki api parser to just return null and quietly error instead of raising an error.
