### ISSUE TITLE
There is a problem with UTRS

### ISSUE THREAD

**Issue by Money12123** [UTRS2/utrs#557]
I recently tried to submit a ticket on the Unblock Ticket Request System on the English Wikipedia, but it said my appeal couldn't be submitted because it was over 4000 characters, even though it was not over 4000 words. I even tried shortening it and it still didn't work. Can this somehow be fixed?

**Comment by dqwiki** [comment]
4000 characters = 4000 letters, numbers, spaces, etc.

You shouldn't need anymore than that to enter your appeal, in fact, most administrators wouldn't review it at that point because it's so long. 4000 characters ~= 1 page

**Comment by Money12123** [comment]
I know this discussion is old, but I tried it again recently and I don't think I'll be able to shorten it, I have to discuss three subjects: sockpuppetry, disruptive edits, and misuse of talk page while trying to get unblocked (which I haven't even written yet and it's already approximately 5,167 characters). Is there anything else I can do?
