### ISSUE TITLE
Ampersand in username breaks Central Auth link

### ISSUE THREAD

**Issue by Cabayi** [UTRS2/utrs#558]
Appeal 58915 for Jiboner&to links to 
https://meta.wikimedia.org/wiki/Special:CentralAuth?target=Jiboner&to
which delivers Central Auth for Jiboner

**Comment by Salvidrim** [comment]
Sounds like the & character needs to be encoded as %26 before being output as an URL, to give the right result:

https://meta.wikimedia.org/wiki/Special:CentralAuth?target=Jiboner%26to
