### ISSUE TITLE
Help me please!!!, I can not create account on Wikipedia.

### ISSUE THREAD

**Issue by Thanaphol-Jitsongkram** [UTRS2/utrs#567]
Hello, politemanfully. Help me please, I can not create account on Wikipedia. I just want to create the new account, I do not know why I am banned from creating new account of Wikipedia. Here are photos showing problem, https://ibb.co/YXzZZKg, https://ibb.co/b3NydX1. Thanks, politemanfully.

**Comment by Salvidrim** [comment]
> Hello, politemanfully. Help me please, I can not create account on Wikipedia. I just want to create the new account, I do not know why I am banned from creating new account of Wikipedia. Here are photos showing problem, https://ibb.co/YXzZZKg, https://ibb.co/b3NydX1. Thanks, politemanfully.

@Thanaphol-Jitsongkram : Hi, you can try requesting an account by following the instructions here: https://en.wikipedia.org/wiki/Wikipedia:Request_an_account

_____________________________________
_This venue is for reporting bugs with the UTRS system, and this is not a bug report._

**Comment by Thanaphol-Jitsongkram** [comment]
> > Hello, politemanfully. Help me please, I can not create account on Wikipedia. I just want to create the new account, I do not know why I am banned from creating new account of Wikipedia. Here are photos showing problem, https://ibb.co/YXzZZKg, https://ibb.co/b3NydX1. Thanks, politemanfully.
> 
> @Thanaphol-Jitsongkram : Hi, you can try requesting an account by following the instructions here: https://en.wikipedia.org/wiki/Wikipedia:Request_an_account
> 
> _This venue is for reporting bugs with the UTRS system, and this is not a bug report._

Thank you, politemanfully.
