### ISSUE TITLE
Automatic unblock.

### ISSUE THREAD

**Issue by riteshmmec** [UTRS2/utrs#579]
If an unblock request is 'Not declined' by any administrator/reviewer within a fixed period (of say 60 days), the unblock request should be accepted automatically after the expiry of the above mentioned period.

**Comment by riteshmmec** [comment]
Otherwise it gives an unfair advantage to administrators who are biased towards any specific point of view.

**Comment by Salvidrim** [comment]
This venue is for reporting bugs with UTRS. 

Your post is not about a bug with UTRS, you are proposing a change to English Wikipedia blocking policy. You can propose changes to English Wikipedia's policies on this Wikipedia discussion board: [https://en.wikipedia.org/wiki/Wikipedia:Village_pump_(policy)](https://en.wikipedia.org/wiki/Wikipedia:Village_pump_(policy))

**Comment by riteshmmec** [comment]
I am currently blocked from editing Wikipedia, therefore unable to propose the same on the suggested discussion page.
