### ISSUE TITLE
Server error - UTRS 2

### ISSUE THREAD

**Issue by xashyar** [UTRS2/utrs#582]
I keep getting this error, whenever I try to make an appeal on https://utrs-beta.wmflabs.org/:

<img src="https://user-images.githubusercontent.com/34171942/193442681-a19dd568-cd2c-4b6a-bbcc-ba031506a3c7.png" width="400" />

**Comment by Salvidrim** [comment]
There have also been reports on WT:UTRS about a lack of new UTRS tickets. https://en.wikipedia.org/wiki/Wikipedia_talk:Unblock_Ticket_Request_System#Should_I_be_concerned?

And I'm not sure what's happening in the history of the UTRS Appels list, DeltaQuadBot seems to be making several edits a second right now: (https://en.wikipedia.org/wiki/User:DeltaQuadBot)

**Comment by dqwiki** [comment]
Ya something went a little haywire with the DB and it got stuck. Will explain more on WT:UTRS.
