### ISSUE TITLE
UTRS bug

### ISSUE THREAD

**Issue by AstroWiki7** [UTRS2/utrs#589]
I have tried to make an appeal several times and it says  that me or someone else is spamming. My previous appeal was closed but it is saying it is not. Then it says that if my appeal was closed, try again later. I have tried it after many hours. Still doesn't work.

**Comment by Salvidrim** [comment]
This does not appear to be a bug with the UTRS system.

If it says your appeal is closed, and then you tried to make several more appeals, that constitutes spamming, and it is reasonable that your ability to file even more UTRS appeals has been correctly disabled at this time.

Your on-wiki appeals have been repeatedly declined, and as you say your UTRS appeal was similarly closed, so it would appear that you will not be able to be unblocked at this time. My personal recommendation would be to find something other than Wikipedia to occupy your time with, and maybe come back with a new unblock request in a few months if you believe you are able to explain why you were originally blocked, and how you would intend to avoid that situation in the future.

For context: [https://en.wikipedia.org/wiki/User_talk:Rihaan_M](https://en.wikipedia.org/wiki/User_talk:Rihaan_M)
