### ISSUE TITLE
alleged Spaming.

### ISSUE THREAD

**Issue by flypie** [UTRS2/utrs#590]
![image](https://user-images.githubusercontent.com/5934895/203326755-ad64d14a-e147-40f3-bcca-5c7549942e02.png)
![image](https://user-images.githubusercontent.com/5934895/203326997-6d96af07-33bc-4197-add4-8b6f0c8f4666.png)

I am receiving this from the UTMS system I have no open appeals.

Additionally, the editor in disarming the claim, states I have made abusive comments on my talk page. There are none.
He also claims that the only use for the talk page is to appeal blocks. I cannot find any such rule anywhere.

The generally snide tone of the Admins comments leads me to believe that they have set the status of the system to prevent me appealing their rath rash decision.

**Comment by Salvidrim** [comment]
GitHub is for reporting technical issues with the UTRS system.

This is not a technical issue with the UTRS system.

Your on-wiki appeals have been repeatedly declined, and your UTRS appeal was similarly closed, so it would appear that you will not be able to be unblocked at this time. My personal recommendation would be to find something other than Wikipedia to occupy your time with until your block expires.
