### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by flypie** [UTRS2/utrs#591]
As you will not this message say's either it is a system problem or I have a complaint open.

![image](https://user-images.githubusercontent.com/5934895/203366771-86e002db-c9ee-4fd2-8632-6ccf8be3a52f.png)

As this msg shows, I don't have a complaint open.

![image](https://user-images.githubusercontent.com/5934895/203367567-a6657acf-67ec-458f-89a9-60a47e11f1a6.png)

So which is it is it a fault in your system or is it an inaccurate msgs that obscures the fact that there is deliberate obstruction by an admin?

**Comment by Salvidrim** [comment]
There is no technical issue and the error message is not inaccurate.

![image](https://user-images.githubusercontent.com/10283535/203370451-942174aa-3fcc-4dbb-ae2c-0f1dfe76bea5.png)

You are not helping your situation by appealing repeatedly on-wiki, then on UTRS, then coming to GitHub. You are intelligent and more reasonable than this. Breathe deeply, walk away, and come back refreshed once your block expires in a few days.
