### ISSUE TITLE
error in using the UTRS system in Wikipedia to appeal a block

### ISSUE THREAD

**Issue by phillman5** [UTRS2/utrs#599]
I am trying to appeal a block on Wikipedia.  I do not seem to have a talk page, as I only once edited a wikipedia entry before, and that was in 2005 or 2006.  So I tried to use the UTRS system.  After submitting my entry it says:

The following errors occurred:
The appealfor field is required.

What in the heck is the appealfor  field.  Where is it?

[Screen Shot 2023-01-19 at 3.35.16 AM.pdf](https://github.com/UTRS2/utrs/files/10455868/Screen.Shot.2023-01-19.at.3.35.16.AM.pdf)

**Comment by dqwiki** [comment]
It would be for your IP address in that case. Did you not fill out an IP address?

**Comment by phillman5** [comment]
Nope, I don't think that is it.  I hit the "Don't know your IP? Get IP address automatically" button.  Which filled out the IP address.

Funny, last night it filled it out IP4, today it filled it out IP6.  But there is nothing I can do with address filled out.  i definitely went into that field and tried to hit <cr>  and it won't let me enter into the field once auto filled out.  Hitting summit button and I get the error, and that field is cleared, and only that field.

I'll go back and manually enter IP address. OK, think I see the problem.  If I go to www.speedtest.net <http://www.speedtest.net/>  if gives me my external IP address.  Did last night just fine, and agreed with the "Don't know your IP? Get IP address automatically" button.  Today,  www.speedtest.net <http://www.speedtest.net/> says a much different IP address and that it is labeled iCloud Private Relay.



_____________________________

       \ _ _ _ _  _ _ /
          ( o    o )
           \      /
            \    /
            (o  o)

**Comment by phillman5** [comment]
I went back and filled out the IP address manually.  It instantly gives 

The following errors occurred:
The appealtext field is required.


_____________________________

       \ _ _ _ _  _ _ /
          ( o    o )
           \      /
            \    /
            (o  o)

**Comment by dqwiki** [comment]
This has been fixed now. I appreciate the report.
