### ISSUE TITLE
Create alpha server

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#61]
alpha-utrs.domain should be made available for developers to test changes as a group or so no one HAS to spawn a local environment to test (though that is optimal). This is some that is needed for #12 to be passed. That said, there are complications.

* Only tool roots can have command line access
* A web-interface allowing the changing of what branch alpha displays would be required
* Only authenticated users could access this interface

@supertassu Should we be creating another repo with a mini-laravel application that could handle this? Or do we have other ideas?

**Comment by supertassu** [comment]
Couple of notes:
* Yes, the application managing UTRS on the alpha server should be separate from UTRS itself. The two main reasons are keeping local envs simpler and not being able to break itself.
  * How should authorization to that be handled? Would it be too meta to use OAuth... for managing the OAuth test instance? :D
  * Related to that, note that my current commit access is only on this repo and not on UTRS2 organization
* Database migration stuff is going to be tricky here
* XFF for that instance needs to be whitelisted on Cloud VPS proxy side, ref [T135046](https://phabricator.wikimedia.org/T135046)

**Comment by dqwiki** [comment]
* Databases will not be an issue as there is a seperate utrs-database2 at this time. The database is purposely separate from the other production instances for security reasons.
* XFF whitelisting will not be granted for that instance. The primary reason being that all on instance testing would generate real private information on testers. I'm not willing to play around with that and old beta instances used a similar policy (and this is a beta of utrs 2, just planned to be hosted on alpha)

**Comment by dqwiki** [comment]
> * Yes, the application managing UTRS on the alpha server should be separate from UTRS itself. The two main reasons are keeping local envs simpler and not being able to break itself.
>   
>   * How should authorization to that be handled? Would it be too meta to use OAuth... for managing the OAuth test instance? :D
>   * Related to that, note that my current commit access is only on this repo and not on UTRS2 organization

Since we've already pushed OAuth, and it now comes in a configurable package thanks to you, yes, lets use that for Authentication. A simple user allowed & admin flag on the user table should be sufficient to manage. This way we can grant access to others without the direct DB. The other thing is we'll need a lockout to make sure only one user is testing files at a time (maybe with an auto-timeout)

We will have to query the github API for the active testing branches.
I'm a little stuck when it comes to the idea of issuing command-line items to the server like git checkout or git pull or git fetch -all, especially from a remote instance.
I could see two laravel instances on the same server and running [exec](https://www.php.net/manual/en/function.exec.php)

If there is an objection to the same server idea, is their really an easy way except for maybe doing an API on server 2 (non-testing) and have server 1 go read that public API result and change to that branch - or do the relevant thing. Seems like more push than worth. If we really crash "sandbox" then it's easy enough to go in with CLI access and fix the issue.

**Comment by dqwiki** [comment]
Alpha server has been created.
