### ISSUE TITLE
Modify reply email

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#622]
- [x] Remove reply link and write do not reply if appeal is closed
- [x] Insert the ~~linked~~ name of the administrator with a wiki signature
- [x] Maybe add a portion about reapplying appeal after x time
- [x] "has been reviewed" - edit to react appropriately to status being set

**Comment by MarcoAurelioWM** [comment]
Sometimes (dealing with abusive users/appeals/globally banned) being able to not display the handling administrator to the appelant would probably be helpful.

**Comment by dqwiki** [comment]
> Sometimes (dealing with abusive users/appeals/globally banned) being able to not display the handling administrator to the appelant would probably be helpful.

@MarcoAurelioWM I'm going to decline your modification to this issue. I understand where you are coming from, but there are a few considerations:
1. The email that gets sent to them when we respond either via Special:EmailUser (#619) or regular email (#626) will come back to me, essentially making me some "supervisor" that I don't want to be.
2. They can still see the responsible admin on the interface with their appeal key regardless of if it's included
3. If its really trolling or abusive, just directly decline (or oversight it) without a response to the user - this will not send them an email. They only get a response if there is something typed in the reply box.

**Comment by MarcoAurelioWM** [comment]
@dqwiki Fair enough. Just a question (I've never used UTRS as a "customer" so pardon my ignorance). I assume it's not our personal emails that get used to send email via EmailUser or directly to the appelant right?

**Comment by dqwiki** [comment]
Correct. Anything sent through Special:EmailUser onwiki uses DeltaQuadBot to send it. Your email address will never be sent to the cx.
