### ISSUE TITLE
DeltaQuadBot: do not reserve appeals when posting a summary of them to SRGP

### ISSUE THREAD

**Issue by MarcoAurelioWM** [UTRS2/utrs#623]
Would it be possible to make DeltaQuadBot not reserve appeals when posting them to SRGP? This will allow stewards to follow-up with the appelant on UTRS without the need to ask a tool admin to force-release it. Thank you!

**Comment by dqwiki** [comment]
Now that it's implemented that we have to check if the appeals have the bot commenting on them already or not, we can do this quite easily.

**Comment by newumed** [comment]
https://www.newumedspaorlando.com/
