### ISSUE TITLE
Email / Notification follow-up for handling administrators

### ISSUE THREAD

**Issue by MarcoAurelioWM** [UTRS2/utrs#624]
I'd find helpful if UTRS could notify me via email of status changes of the appeals I am the handling administrator. If e.g. I set an appeal as "awaiting reply" and the appelant does indeed reply, getting a notification via email (and/or one built-in in the app) could be useful. Right now I have to browse the entire list of appeals awaiting reply to see if any has changed status.

Receiving notifications should be optional via a user preference, and it'd be good if for administrators with access to several queues, we could choose for which one we'd like to receive these.

Thank you.

**Comment by dqwiki** [comment]
Closing now duplicated by #626
