### ISSUE TITLE
Grant translator rights to maurelio at translation.io

### ISSUE THREAD

**Issue by MarcoAurelioWM** [UTRS2/utrs#625]
In order to update the Spanish translations and while this project is not yet available in translatewiki.net (not sure what is your decision regarding that), please grant translation.io account `maurelio` Spanish translation rights in the UTRS project over there. Confirming that said account over there is me. Thank you.

**Comment by dqwiki** [comment]
@MarcoAurelioWM done. Please file an issue (or reopen if you have new translations for the same language) whenever you have a stack of updates so that I can make a pull request and get it in the code. translatewiki is in progress but waiting on Martin Urbanec.

**Comment by MarcoAurelioWM** [comment]
Thank you, will do. I appreciate your time as always. Best regards.
