### ISSUE TITLE
System service not started after downtime

### ISSUE THREAD

**Issue by DeirgeDel** [UTRS2/utrs#631]
We apologise for any inconvenience caused. Please report this exception at https://github.com/utrs2/utrs/issues.

If this happened while creating your appeal, do not create another appeal as it might have been saved. Instead, contact UTRS developers at [utrs-developers@googlegroups.com](mailto:utrs-developers@googlegroups.com) so they can help you.

Occurred Circa 2023-02-12 18:40 UTC

(https://utrs-beta.wmflabs.org/public/appeal/account) 

Reporting as requestred.

**Comment by dqwiki** [comment]
Thank you, sorry I didn't see this sooner. I assume it's related to my security fixes. I'll go look at the error

**Comment by dqwiki** [comment]
@DeirgeDel Thanks for the report. After the downtime we had earlier today, one of the system critical modules that gets rebooted overnight wasn't running and was causing the issue. I started the service and everything seemingly works without issue.
