### ISSUE TITLE
Admin comments

### ISSUE THREAD

**Issue by Liefernando1** [UTRS2/utrs#640]
When is admin comment in UTRS? It is new comment from Liefernando1 after the previous appeal was closed. It is been a long time since there has been a comment from the admin at UTRS.

**Comment by dqwiki** [comment]
You can't file an appeal and expect an immediate response. It can take
several days sometimes weeks. Either way, the developers here are not
responsible for the timeline that people respond. This is only for issues
in the software itself. Please do not abuse this function.

AmandaNP
UTRS Developer
