### ISSUE TITLE
Unblock requests won't send

### ISSUE THREAD

**Issue by Isaacarthy** [UTRS2/utrs#645]
Earlier today, I made an unblock request for my Wikipedia account (user:Isaacarthy), but after misplacing my recovery code, I decided to make another request. However, whenever I do this, it doesn't go through, saying the requests are being spammed or something (I can't make unblock requests on my talk page as I've also been blocked from editing on there). Can someone look into this?

**Comment by dqwiki** [comment]
Please forward the initial email you received from the interface (if your wiki account has email enabled) to utrs-developers@googlegroups.com
If you don't have email enabled, you will need to find some way to send me (User:AmandaNP) acceptable proof that you control the account.
If you are locked, don't have email enabled and can't login, then you will have to restart your appeal as I can't verify your identity and disclose the information in the appeal.

Either way, any further questions should be handled through utrs-developers@googlegroups.com as this is not a bug, but a end user issue. Thanks.
