### ISSUE TITLE
Can't appeal an auto-block on Wikipedia

### ISSUE THREAD

**Issue by Ramones77** [UTRS2/utrs#648]
I'm blocked and I did nothing wrong. Tried to do an appeal on the auto-block, but was unable to do so as this warning appeared:

"Uh-oh. UTRS has suffered an internal exception and can't continue to serve your request.

We apologise for any inconvenience caused. Please report this exception at https://github.com/utrs2/utrs/issues.

If this happened while creating your appeal, do not create another appeal as it might have been saved. Instead, contact UTRS developers at [utrs-developers@googlegroups.com](mailto:utrs-developers@googlegroups.com) so they can help you."

Thank you

**Comment by dqwiki** [comment]
This issue has been fixed. Thank you for your attention.
