### ISSUE TITLE
Missed pagefix in fixing security bug

### ISSUE THREAD

**Issue by DeirgeDel** [UTRS2/utrs#670]
Sequence: 

* Admin indicates appeal is closed on my Djm-leighpark talk page - alt of (Djm-leighpark is an alt. account of DeirgeDel but regarded as main account on the English Wikipedia)
* https://en.wikipedia.org/w/index.php?title=User_talk%3ADjm-leighpark&diff=1152336761&oldid=1149933735
* Provided link is here: https://utrs-beta.wmflabs.org/appeal/70412
* When I enter my appeal the the URL https://utrs-beta.wmflabs.org/public/appeal/view?hash=REDACTEDAPPEALKEY has the response:

Oops! An Error Occurred
The server returned a "405 Method Not Allowed".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Time of error was about 1 May 2023 21:00 UTC approx.

I have seen this before and know the workaround is to use https://utrs-beta.wmflabs.org/ where the "View my appeal" does work.  However I thought I may have used an inappropriate pathway to that page so I ignored it.  However as the UTRS appeal closer has placed the link on the talk page it certainly needs to work for people who has no access to their talk page.

Thankyou.

**Comment by dqwiki** [comment]
Thank you for this report. I will have to investigate this. I think this may be the one part I missed in fixing the 4 pages affected by GHSA-p247-r7fj-jmm5. So I will add this to my list to investigate this.
