### ISSUE TITLE
Lack of hint at length of spam lock/no contact address

### ISSUE THREAD

**Issue by mirddes** [UTRS2/utrs#688]
It has been detected that you or someone else is trying to spam our system with appeals. Please wait until your previous appeal is closed, or if it is already closed, please try again later. If you are applying for an unblock of an IP address, this could mean that an appeal has already been submitted for your IP. In this case, please try again later or contact us to help clarify the issue.

**Comment by dqwiki** [comment]
I honestly thought we still had the email up there. I don't know when it disappears, but I will readd it. I will also add the disclaimer though that we won't be able to help with the unblock request.
As far as the timeline, an exact figure will never be given, as it's meant to add a cooldown for you to think about what the previous administrator has said. It's to stop people from coming back exactly on that time and filing the exact same appeal and wasting the time of the admins. Either way, a hint could still be used.
I will make these changes later today.

**Comment by mirddes** [comment]
thank you. 
the email i subsequently got said "a few days" which is a suitably vaguely specfic hint.

live long and prosper.
and may the force be with you always.
