### ISSUE TITLE
Wikipedia error

### ISSUE THREAD

**Issue by Ocobelo** [UTRS2/utrs#692]
While trying to view my block appeal status on Wikipedia, I received the following error after entering my block appeal key:

The server returned a "405 Method Not Allowed"

**Comment by dqwiki** [comment]
It's likely a version of GHSA-p247-r7fj-jmm5 from a ticket done before that fix. If you need the content of a previous appeal under that, hit up the dev email.
If it's a new ticket, please explain how you are getting to this.

**Comment by dqwiki** [comment]
No response yet, we can review if this is actually an issue.
