### ISSUE TITLE
Fix unit testing for PRs

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#70]
See https://github.com/UTRS2/utrs/actions/runs/105414200

**Comment by supertassu** [comment]
Worked just well on https://github.com/UTRS2/utrs/actions/runs/105446379. Will investigate if they will fail again.

**Comment by supertassu** [comment]
They've not failed since that one case. Please shout if they start failing again and I'll reopen.

**Comment by dqwiki** [comment]
https://github.com/UTRS2/utrs/actions/runs/106150185

**Comment by supertassu** [comment]
All failures I've seen have been simple fixes that have been merged immediately after opening. My guess here is that tests only fail if the PR has been merged before the test pipeline can run `actions/checkout`.

**Comment by dqwiki** [comment]
Oh that's an interesting aspect. I'll be sure to let it run in the future if it's not an urgent fix.
