### ISSUE TITLE
Environment type can crash ip functions

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#73]
A lot of the app uses `$ip = $request->server('HTTP_X_FORWARDED_FOR');` to determine the IP. This is great for a our production environment, as it's what it should be, but not for other productions or any locals.

Using a new use_xff config var to fix this.

**Comment by supertassu** [comment]
How about just using `$request->ip()` now that the app was configured to trust XFF from CloudVPS proxies?
