### ISSUE TITLE
UTRS has suffered an internal exception and can't continue to serve your request

### ISSUE THREAD

**Issue by Westlander11** [UTRS2/utrs#751]
![utrs2](https://github.com/UTRS2/utrs/assets/154639643/99e3dc89-0d34-4c70-add2-f80d1bec7a67)
 how do i get rid of this

**Comment by Westlander11** [comment]
I was trying to make an appeal for my account which was falsely accused of "sockpuppeting" someone I don't know on Wikipedia.

**Comment by dqwiki** [comment]
This was an internal issue that my system wasn't reporting to me. The issue is now fixed and you can appeal.
