### ISSUE TITLE
Unblock Request Error

### ISSUE THREAD

**Issue by AaishaAfzaal** [UTRS2/utrs#764]
As my account was blocked and I requested unblock through Unblock Ticket Request System against the following Wikipedia IP and account unblock appeal keys but, its giving me error on checking the status. Please help in this regard and resolve the unblock request. 

[redacted keys]

Thank you

**Comment by dqwiki** [comment]
The red message simply states that the appeals are closed - it's not a bug.

Also please do not post appeal keys here.
