### ISSUE TITLE
internal exception on Appeal my block page

### ISSUE THREAD

**Issue by greghenderson2006** [UTRS2/utrs#765]
I get this message when I click on Blocked user Appeal my block here: https://utrs-beta.wmflabs.org

Uh-oh. UTRS has suffered an internal exception and can't continue to serve your request.
We apologise for any inconvenience caused. Please report this exception at https://github.com/utrs2/utrs/issues.

If this happened while creating your appeal, do not create another appeal as it might have been saved. Instead, contact UTRS developers at [utrs-developers@googlegroups.com](mailto:utrs-developers@googlegroups.com) so they can help you.

**Comment by dqwiki** [comment]
Please try again and re-report if you are having issues.
