### ISSUE TITLE
Uh-oh. UTRS has suffered an internal exception and can't continue to serve your request.

### ISSUE THREAD

**Issue by Fgju** [UTRS2/utrs#769]
![image](https://github.com/user-attachments/assets/6b04f3f1-2ca0-43b3-8712-80acaa7bd125)
That's what I know...

**Comment by dqwiki** [comment]
Reviewing by email for sensitive information

**Comment by scottbb** [comment]
Same thing happened to me. I didn't receive any more information than the screen shot in this ticket.

**Comment by dqwiki** [comment]
@scottbb I'm not sure when yours was submitted, so I don't have an error log that I can look at.
@Fgju Yours appears to be that the wikipedia database was struggling at the time. You are fine to try again - they've been struggling the past few days

**Comment by dqwiki** [comment]
Now fixed in c256a062bfbb70d9c40b6cd8d4e4c11049cc3616
