### ISSUE TITLE
AGAIN SO ARE WE BANNED FROM APPEALLING?!?!?!

### ISSUE THREAD

**Issue by ihearttriplebaka** [UTRS2/utrs#773]
_(image removed by moderation)_

**Comment by ihearttriplebaka** [comment]
oops wrong image

**Comment by ihearttriplebaka** [comment]
![Screenshot 2024-07-22 155332](https://github.com/user-attachments/assets/18ae24d2-4264-454c-9aa0-00787d757263)

**Comment by Whydidthechickencrosstheroad** [comment]
Yeah, that happened to me also

**Comment by dqwiki** [comment]
Now fixed in c256a062bfbb70d9c40b6cd8d4e4c11049cc3616

**Comment by dqwiki** [comment]
@ihearttriplebaka Per your comment on the commit, you should be able to appeal now. Please try again.
