### ISSUE TITLE
I see this error message:

### ISSUE THREAD

**Issue by Whydidthechickencrosstheroad** [UTRS2/utrs#785]
I am seeing this but I don't know what is going on here
![image](https://github.com/user-attachments/assets/ec10593c-91f1-42bb-836c-330e9b1d90ae)

**Comment by Whydidthechickencrosstheroad** [comment]
Please fix this quickly. It is a real emergency

**Comment by dqwiki** [comment]
This is not a real emergency. None the less, it has been fixed, and yet another mitigation has been put in place to stop it...hopefully.

**Comment by Whydidthechickencrosstheroad** [comment]
Ok, thanks. It is fixed now
