### ISSUE TITLE
blocked code #1019

### ISSUE THREAD

**Issue by mrick360** [UTRS2/utrs#790]
I wish to participate in the Wikipedia website but am unable to because of this obtuse blockage.  Yes, I have a T-Mobile 5G home internet service.  But I am unfairly being punished for a non-existing vandalism charge placed on my ISP.  I would think that you, as intelligent people, could come up with a solution to allow innocent users to use services like Wikipedia.  This is actually a Constitutional violation by banning innocent users from using your service WITHOUT ANY evidence of wrongdoing. A widespread ban on the general public is not legal.

**Comment by JayCubby-enwiki** [comment]
Copyright Randall Munroe (CC BY-SA NC)
![image](https://github.com/user-attachments/assets/341da7fa-16ce-486e-b52d-da9ac9ac585a)

**Comment by mrick360** [comment]
YouTube's removal of your comment or replies to a video IS an organized violation of free speech in which the government is a party of.  This is proven in Congressional hearings and have been shown on YouTube an other forums.
    On Monday, October 14, 2024 at 07:26:29 PM CDT, JayCubby-enwiki ***@***.***> wrote:  
 
 


Copyright Randall Munroe (CC BY-SA NC)
image.png (view on web)

**Comment by mrick360** [comment]
The government controls the actions of entities that produce internet, television, and telephone content.  It is a violation of Constitutional rights to punish innocent individuals for the actions of a few in their area.  If the government does not restrict this action IT IS A VIOLATION OF CONSTITUTIONAL RIGHTS.
    On Tuesday, October 15, 2024 at 11:11:59 AM CDT, Darryl Jones ***@***.***> wrote:  
 
  YouTube's removal of your comment or replies to a video IS an organized violation of free speech in which the government is a party of.  This is proven in Congressional hearings and have been shown on YouTube an other forums.
    On Monday, October 14, 2024 at 07:26:29 PM CDT, JayCubby-enwiki ***@***.***> wrote:  
 
 


Copyright Randall Munroe (CC BY-SA NC)
image.png (view on web)
