### ISSUE TITLE
Add useful links to navbar to logged in users / users with permissions

### ISSUE THREAD

**Issue by supertassu** [UTRS2/utrs#90]
The current navbar is empty. We could add some useful links such as appeal list or template/user/ban management.

This is much easier when #106 is merged as that allows using `@can('viewAny', \App\Template::class)` styled statements in blade files.

**Comment by dqwiki** [comment]
If you wanted to add the Admin functions, you could do so as a drop down, but maybe disable or at least give a notice for ones not working.
